# Generated by cucumber-sinatra. (2010-10-07 22:39:37 +0100)

require File.join(File.dirname(__FILE__), '..', '..', 'app.rb')

require 'capybara'
require 'capybara/cucumber'
require 'spec'

DaKroken.set(:environment, :test)

Capybara.app = DaKroken

class DaKrokenWorld
  include Capybara
  include Spec::Expectations
  include Spec::Matchers
end

World do
  DaKrokenWorld.new
end
